package com.model;

public class CoinByExchange {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column coin_by_exchange.id
	 * 
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column coin_by_exchange.id_coin
	 * 
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	private Coin coin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column coin_by_exchange.id_exchange
	 * 
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	private Exchange exchange;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column coin_by_exchange.api_name
	 * 
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	private String apiName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column coin_by_exchange.id
	 * 
	 * @return the value of coin_by_exchange.id
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column coin_by_exchange.id
	 * 
	 * @param id
	 *            the value for coin_by_exchange.id
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column coin_by_exchange.api_name
	 * 
	 * @return the value of coin_by_exchange.api_name
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	public String getApiName() {
		return apiName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column coin_by_exchange.api_name
	 * 
	 * @param apiName
	 *            the value for coin_by_exchange.api_name
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	public void setApiName(String apiName) {
		this.apiName = apiName;
	}

	public Coin getCoin() {
		return coin;
	}

	public void setCoin(Coin coin) {
		this.coin = coin;
	}

	public Exchange getExchange() {
		return exchange;
	}

	public void setExchange(Exchange exchange) {
		this.exchange = exchange;
	}
}