package com.model;

import java.math.BigDecimal;
import java.util.Date;

public class Quotation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column quotation.id
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column quotation.id_coin_by_exchange
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	private CoinByExchange coinByExchange;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column quotation.satoshis
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	private BigDecimal satoshis;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column quotation.timestamp
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	private Date timestamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column quotation.id
	 * @return  the value of quotation.id
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column quotation.id
	 * @param id  the value for quotation.id
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}



	public CoinByExchange getCoinByExchange() {
		return coinByExchange;
	}

	public void setCoinByExchange(CoinByExchange coinByExchange) {
		this.coinByExchange = coinByExchange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column quotation.satoshis
	 * @return  the value of quotation.satoshis
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	public BigDecimal getSatoshis() {
		return satoshis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column quotation.satoshis
	 * @param satoshis  the value for quotation.satoshis
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	public void setSatoshis(BigDecimal satoshis) {
		this.satoshis = satoshis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column quotation.timestamp
	 * @return  the value of quotation.timestamp
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	public Date getTimestamp() {
		return timestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column quotation.timestamp
	 * @param timestamp  the value for quotation.timestamp
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}
}