package com.model;

import java.math.BigDecimal;
import java.util.Date;

public class Quotation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column quotation.id
	 * 
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column quotation.id_coin_by_exchange
	 * 
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	private CoinByExchange coinByExchange;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column quotation.satoshis
	 * 
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	private BigDecimal satoshis;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column quotation.timestamp
	 * 
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	private Date timestamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column quotation.id
	 * 
	 * @return the value of quotation.id
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column quotation.id
	 * 
	 * @param id
	 *            the value for quotation.id
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	public CoinByExchange getCoinByExchange() {
		return coinByExchange;
	}

	public void setCoinByExchange(CoinByExchange coinByExchange) {
		this.coinByExchange = coinByExchange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column quotation.satoshis
	 * 
	 * @return the value of quotation.satoshis
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	public BigDecimal getSatoshis() {
		return satoshis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column quotation.satoshis
	 * 
	 * @param satoshis
	 *            the value for quotation.satoshis
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	public void setSatoshis(BigDecimal satoshis) {
		this.satoshis = satoshis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column quotation.timestamp
	 * 
	 * @return the value of quotation.timestamp
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	public Date getTimestamp() {
		return timestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column quotation.timestamp
	 * 
	 * @param timestamp
	 *            the value for quotation.timestamp
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Quotation [id=").append(id).append(", coinByExchange=").append(coinByExchange)
				.append(", satoshis=").append(satoshis).append(", timestamp=").append(timestamp).append("]");
		return builder.toString();
	}

	/**
	 * @return
	 * @see com.model.CoinByExchange#getCoin()
	 */
	public Coin getCoin() {
		return coinByExchange.getCoin();
	}

	/**
	 * @param coin
	 * @see com.model.CoinByExchange#setCoin(com.model.Coin)
	 */
	public void setCoin(Coin coin) {
		coinByExchange.setCoin(coin);
	}

	/**
	 * @return
	 * @see com.model.CoinByExchange#getExchange()
	 */
	public Exchange getExchange() {
		return coinByExchange.getExchange();
	}

	/**
	 * @param exchange
	 * @see com.model.CoinByExchange#setExchange(com.model.Exchange)
	 */
	public void setExchange(Exchange exchange) {
		coinByExchange.setExchange(exchange);
	}

}