package com.model;

public class UserGroup {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_group.id
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_group.id_group
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	private Integer idGroup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_group.id_user
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	private Integer idUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_group.is_manager
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	private Boolean isManager;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_group.id
	 * @return  the value of user_group.id
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_group.id
	 * @param id  the value for user_group.id
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_group.id_group
	 * @return  the value of user_group.id_group
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	public Integer getIdGroup() {
		return idGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_group.id_group
	 * @param idGroup  the value for user_group.id_group
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	public void setIdGroup(Integer idGroup) {
		this.idGroup = idGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_group.id_user
	 * @return  the value of user_group.id_user
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	public Integer getIdUser() {
		return idUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_group.id_user
	 * @param idUser  the value for user_group.id_user
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_group.is_manager
	 * @return  the value of user_group.is_manager
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	public Boolean getIsManager() {
		return isManager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_group.is_manager
	 * @param isManager  the value for user_group.is_manager
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	public void setIsManager(Boolean isManager) {
		this.isManager = isManager;
	}
}