package com.model;

import java.util.Date;

public class UserInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.id
	 * 
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.login
	 * 
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	private String login;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.creation_timestamp
	 * 
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	private Date creationTimestamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.id
	 * 
	 * @return the value of user.id
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.id
	 * 
	 * @param id
	 *            the value for user.id
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.login
	 * 
	 * @return the value of user.login
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	public String getLogin() {
		return login;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.login
	 * 
	 * @param login
	 *            the value for user.login
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	public void setLogin(String login) {
		this.login = login;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.creation_timestamp
	 * 
	 * @return the value of user.creation_timestamp
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	public Date getCreationTimestamp() {
		return creationTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.creation_timestamp
	 * 
	 * @param creationTimestamp
	 *            the value for user.creation_timestamp
	 * @mbg.generated Tue Jan 09 18:29:23 CET 2018
	 */
	public void setCreationTimestamp(Date creationTimestamp) {
		this.creationTimestamp = creationTimestamp;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("UserInfo [id=").append(id).append(", login=").append(login).append(", creationTimestamp=")
				.append(creationTimestamp).append("]");
		return builder.toString();
	}
}