package com.client;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.model.CoinPerUser;

public interface CoinPerUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coin_per_user
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coin_per_user
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int insert(CoinPerUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coin_per_user
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int insertSelective(CoinPerUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coin_per_user
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	CoinPerUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coin_per_user
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int updateByPrimaryKeySelective(CoinPerUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coin_per_user
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int updateByPrimaryKey(CoinPerUser record);
	
	List<CoinPerUser> selectByUserID(Integer userID);
	
	List<CoinPerUser> selectByUserLogin(String userLogin);

	List<CoinPerUser> selectByUserCryptoExcange(@Param("userLogin") String userLogin, @Param("idCrypto") Integer idCrypto, @Param("idExchange") Integer idExchange);
}