package com.client;

import java.util.List;

import com.model.Coin;

public interface CoinMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coin
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coin
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int insert(Coin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coin
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int insertSelective(Coin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coin
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	Coin selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coin
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int updateByPrimaryKeySelective(Coin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coin
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int updateByPrimaryKey(Coin record);
	
	Coin selectByName(Coin record);
	
	List<Coin> selectAll();
}