package com.client;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.model.CoinByExchange;

public interface CoinByExchangeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coin_by_exchange
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coin_by_exchange
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int insert(CoinByExchange record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coin_by_exchange
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int insertSelective(CoinByExchange record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coin_by_exchange
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	CoinByExchange selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coin_by_exchange
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int updateByPrimaryKeySelective(CoinByExchange record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coin_by_exchange
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int updateByPrimaryKey(CoinByExchange record);

	List<CoinByExchange> getAll();
	
	CoinByExchange selectByCoinExchange(@Param("coinId") Integer coinId, @Param("exchangeId") Integer exchangeId);
}