package com.client;

import com.model.ExchangeApi;

public interface ExchangeApiMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exchange_api
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exchange_api
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int insert(ExchangeApi record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exchange_api
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int insertSelective(ExchangeApi record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exchange_api
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	ExchangeApi selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exchange_api
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int updateByPrimaryKeySelective(ExchangeApi record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exchange_api
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int updateByPrimaryKey(ExchangeApi record);
}