package com.client;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.model.Exchange;

public interface ExchangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbg.generated Tue Jan 09 18:29:23 CET 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbg.generated Tue Jan 09 18:29:23 CET 2018
     */
    int insert(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbg.generated Tue Jan 09 18:29:23 CET 2018
     */
    int insertSelective(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbg.generated Tue Jan 09 18:29:23 CET 2018
     */
    Exchange selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbg.generated Tue Jan 09 18:29:23 CET 2018
     */
    int updateByPrimaryKeySelective(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbg.generated Tue Jan 09 18:29:23 CET 2018
     */
    int updateByPrimaryKey(Exchange record);
    
    Exchange selectByName(@Param("exchange") String exchange);
    
    List<Exchange> selectAll();
}