package com.client;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.model.Coin;
import com.model.Exchange;
import com.model.Quotation;

public interface QuotationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quotation
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quotation
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int insert(Quotation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quotation
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int insertSelective(Quotation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quotation
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	Quotation selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quotation
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int updateByPrimaryKeySelective(Quotation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quotation
	 * @mbg.generated  Tue Jan 09 18:29:23 CET 2018
	 */
	int updateByPrimaryKey(Quotation record);
	
	Quotation getLastExchangeCoin(Quotation record);
	
	List<Quotation> selectByBuyDate(@Param("coin") Coin coin, @Param("exchange") Exchange exchange, @Param("buyDate") Date buyDate);
	
	Quotation selectCoinByDate(@Param("coin") Coin coin, @Param("exchange") Exchange exchange, @Param("buyDate") Date buyDate);
	
	List<Quotation> selectAllByCoinExchange(@Param("coin") Coin coin, @Param("exchange") Exchange exchange);
}