INSERT INTO COIN (NAME, SHORT_NAME, FINAL) VALUES('Bitcoin', 'BTC', false);
INSERT INTO COIN (NAME, SHORT_NAME, FINAL) VALUES('Euro', 'EUR', true);
INSERT INTO COIN_BY_EXCHANGE (ID_COIN, ID_EXCHANGE, ID_COIN_PAIR) VALUES((SELECT ID FROM COIN WHERE SHORT_NAME = 'BTC'), (SELECT ID FROM EXCHANGE WHERE NAME = 'GDAX'), (SELECT ID FROM COIN WHERE SHORT_NAME = 'EUR'));
INSERT INTO USER_INFO (LOGIN, CREATION_TIMESTAMP) VALUES ('a', LOCALTIMESTAMP);